### ISSUE TITLE
Switch methods from private to protected

### ISSUE THREAD

**Issue by tof43** [dvdoug/BoxPacker#167]
Hello,

It would be great if you could switch Packer methods from private to protected. This would allow to override them in order to implement custom treatment.
In my case, I have implemented some custom checks in findBestBoxFromIteration().

Many thanks, and congratulation for the awesome work by the way !

**Comment by dvdoug** [comment]
Hello

Happy in theory to consider doing this on a case by case basis - I currently have most of them private because I change the underlying abstractions from time to time as the algorithm gets improved and anything that's public or protected makes that a lot more difficult to do as semver means that would need a major version API bump.

What are the changes you've made - are they super-specific to your use case or would those types of check be useful to a wider audience?

**Comment by dvdoug** [comment]
@tof43 ?

**Comment by tof43** [comment]
Hello,

I am really sorry, I missed the first reply... Well, in my case I have additionnal check on boxes. For example, for each box I can specify a minimal size that the packed product must respect. I have added the check in findBestBoxFromIteration.
