### ISSUE TITLE
v2.6 Slow to pack

### ISSUE THREAD

**Issue by glennjacobs** [dvdoug/BoxPacker#179]
I'm running v2.6 and I have an example where I'm trying to pack 27 items. It's taking on average 75 seconds to complete.

This is too slow for my requirements. Is there any way to improve performance?

I've not got xdebug running, but I am limited to PHP 5.6 unfortunately.

**Comment by glennjacobs** [comment]
Also worth noting I have 5 box sizes.

**Comment by glennjacobs** [comment]
Interestingly, downgrading to v2.4.8 increases the speed drastically!

I've gone from 60 - 70 seconds to 4 seconds.

**Comment by glennjacobs** [comment]
v2.5.0 seems to be fast also, seems 2.6.0 slows things down for some reason?

**Comment by glennjacobs** [comment]
I tried v2.1 also, and it's mega quick! only 65ms!

**Comment by dvdoug** [comment]
There's a balance I try to strike - trading off efficiency of packing for efficiency of time. Unfortunately, it turns out the SPL data structures that were used in v2 are more cumbersome than helpful and so v2 is slower than v3 :(

I've just released 2.6.1 with some additional optimisations - does it restore expected speed for you?

**Comment by dvdoug** [comment]
Assuming it has, please reopen if not with a testcase
