### ISSUE TITLE
ItemList is destroyed after calling $volumePacker->pack()

### ISSUE THREAD

**Issue by Noodleyman** [dvdoug/BoxPacker#186]
This is tripping me up a little, although I can work around it. I am not sure if this is by design or not.

In my situation, I've packed Hazardous materials into special boxes as a first pass. I am then evaluating as a second phase if I can fit non-hazardous materials into the same box.

To do this, I pull the items out the packed box into an ItemList, then add an extra item to that list. I pass the list and box attributes to $volumePacker->pack() so I can evaluate if the extra item may be thrown into the same box.

If yes, repeat the process until either all items are packed, or we can't fit any more non-hazardous items into the same box.

However, each time I pass the list to the pack() method, the list is destroyed so I need to go back and rebuild it again.  

I had hoped that I can take the firmed up list of Packed items and re-use it for each iteration for efficiency. 

Thought I would raise the question here:
Should ItemList get destroyed after using volumePacker pack() method?

The issue is reproducible using the documented example here:
https://www.boxpacker.io/en/stable/getting-started.html#packing-a-set-of-items-into-a-given-set-of-box-types

**Comment by dvdoug** [comment]
It's not by design in the sense that I've ever thought about it before, it's just a natural consequence of the algorithm calling `->extract` repeatedly on it.

But `Packer` does a `clone` when setting an `ItemList` (see https://github.com/dvdoug/BoxPacker/blob/master/src/Packer.php#L76) so happy to make `VolumePacker` do the same for consistency
