### ISSUE TITLE
Placement method Issue! Help please

### ISSUE THREAD

**Issue by sipekiattila** [dvdoug/BoxPacker#201]
Hello Dvdoug!

Can you please share me you opinion about my issue? I would like to ask you where can I modify the code to get this result of the boxes? Every time when the code is calculate the boxes are in one column.

![Packer](https://user-images.githubusercontent.com/63288143/80022304-249a8780-84dc-11ea-8b15-eb21df091950.PNG)

But I need in this way:

![Packer2](https://user-images.githubusercontent.com/63288143/80022402-4d228180-84dc-11ea-8bf1-7cf6cb29ec07.png)

like this:
![Packer3](https://user-images.githubusercontent.com/63288143/80022514-78a56c00-84dc-11ea-8e7c-a7ee4c9ef568.PNG)

Thank you in advance!

**Comment by dvdoug** [comment]
Hi @sipekiattila 

BoxPacker works by packing things in "rows". To get the effect you want you'll need to therefore force the library to pack across the shorter dimension rather than the longer one.

In v3.6.0 (tagged a few minutes ago) the relevant code is located at https://github.com/dvdoug/BoxPacker/blob/master/src/VolumePacker.php#L104, you'll need to ensure that `$boxWidth` is the shorter dimension in your diagram, and `$boxLength` is the longer one. From 3.6.0 onwards, the library will normally try both orientations so you'll need to disable that.

In earlier versions, the code is located at https://github.com/dvdoug/BoxPacker/blob/3.5.2/src/VolumePacker.php#L102 - again you'll need to adjust that so the width is considered to be the shorter dimension rather than the longer.

What's the use case you have for needing the items to be at one end?

**Comment by alexvremja** [comment]
truck load?
