### ISSUE TITLE
Add support float type

### ISSUE THREAD

**Issue by Gemorroj** [dvdoug/BoxPacker#215]
https://github.com/dvdoug/BoxPacker/blob/3.x/src/Box.php and https://github.com/dvdoug/BoxPacker/blob/3.x/src/Item.php use integers, but in real life we oftent manipulate float numbers. `0.3 kg` for example.

please, add support float type.

**Comment by dvdoug** [comment]
Hi @Gemorroj 

The dimensions are specified in grams, so you'll need to multiply by 1000 if your own base unit is kilograms (I assume you already worked that bit out).

The specific reason for requiring integers rather than floats is because simple float comparisons for equality are unsafe, and the library does a lot of `<=` calculations. See the code at https://3v4l.org/MHVoX for a simple example of how things can quickly go wrong when using floats.

![image](https://user-images.githubusercontent.com/1571110/98448340-36afe080-2123-11eb-8d1b-3e609f55693e.png)

So integers are here to stay, sorry
