### ISSUE TITLE
Box packing issue

### ISSUE THREAD

**Issue by hmza27** [dvdoug/BoxPacker#271]
Hi,
The algorithm is not returning the correct box the items fit in a smaller box but instead it returns a bigger box can you help me with this.
Thanks

**Comment by dvdoug** [comment]
Hi @hmza27 

Can you supply more information?

**Comment by hmza27** [comment]
Hi the items are
1st item value in inches are
width:203.2
lenght:203.2
height:12.7
I am adding it with quantity of 4
2nd item value in inches are
width:304.8
lenght:381
height:76.2
I am adding it with quantity of 2
And the two boxes values are:
1st box (large one):
outerwidth:396.875
outerLength:320.675
outerDepth:177.8
innerWidth:400.05
innerLength:320.675
innerDepth:177.8
2nd box (small one):
outerwidth:396.875
outerLength:320.675
outerDepth:101.6
innerWidth:396.875
innerLength:317.5
innerDepth:98.425
The items should come in the small box but it's been packed in the large one
Thanks

**Comment by shakethatweight-simon** [comment]
@hmza27  I'm not the developer, but I do use this BoxPacker in our software. 

1. The dimensions are expected to be integer, not float.

2. I also note that the inner and outer _length_ of box 1 are the same, and inner and outer _width_ of box 2 are the same, is this intentional?

3. Just by checking the total overall volume, I don't see how they can fit in the small box.

Total volume of items: `4 * 203.2 * 203.2 * 12.7 + 2 * 304.8 * 381 * 76.2 = 19,795,573.312`
Total volume of small box: `396.875 * 317.5 * 98.425 = 12,402,318.9453`

19 (item volume) > 12 (box volume) so the items can't fit.
