### ISSUE TITLE
$packedBox->RemainingWidth in test is same as box inner width

### ISSUE THREAD

**Issue by compadvance** [dvdoug/BoxPacker#42]
Which doesn't make sense at all. How can you put item in box and make remaining width same.

Also this leads to my question - I want to get get how much space (HxDxL) packed items has used in $PackedBox

**Comment by dvdoug** [comment]
Hi

Not sure which line you are looking at? Can you give me a file name and a line number?

For your second question, are you looking for the pure volume of the items in the box (i.e. sum of the individual HxDxL), or the total space used including any gaps in the packing (i.e. if you were to create a custom box for this particular packing, the size of the box you would need).

**Comment by compadvance** [comment]
If you run test from readme.md and if you execute

    echo $packedBox->getRemainingWidth();

you will get same value as innerwidth

Regarding second question, I am looking for total space used including gaps (basically InnerWidth-GetRemainingWidth)

**Comment by dvdoug** [comment]
In the example from the readme (assuming you're referrring to the second one?), items 1 and 2 don't fit because they are both 1mm too wide.

The only item that fits is item 3, which is 296x296x4. As the inner dimensions of the box are 296x296x*8*, there is an unused void of 296x296x4 above item 3, hence the remaining width being reported as 296.

For the total space info, I don't think you can calculate this from the information currently stored - remaining width/length/depth will tell you the maximum size of item the algorithm is willing to put into the box at that point, but as items are packed vertically, the space used decreases (it's like a pyramid) as you wouldn't try to pack a large item on top of a smaller one.

I think you'd need to modify the algorithm to keep track of the *largest* layer size it packed through each iteration and return that at the end.
