### ISSUE TITLE
Don't understand how to use.

### ISSUE THREAD

**Issue by darryljackman** [dvdoug/BoxPacker#48]
I have never heard of composer, and don't want to install anything, mostly for portability reasons, and move between Mac, Windows and Linux servers almost daily.

Is there a normal way to use this, like just including a file?

I'm not sure why this is more complicated than other php classes I've seen, maybe it's just over my head, but I have no idea how to be able to start to use this, and I've been dealing with PHP for years!!

EDIT: Saw in another closed issue a similar comment about using standalone with any kind of composer, and the reply in general said to include all the files and then can use. I tried including the files and not doing anything else, and get "PHP Fatal error:  Interface 'Psr\Log\LoggerAwareInterface' not found in /home/marine/public_html/crm/helpers/BoxPacker/Packer.php on line 20"

Maybe would be easier to try and implement this functionality myself, which is a shame because looks like a lot of effort went in to this, but don't think I will be able to get it to work :(

**Comment by dvdoug** [comment]
Composer is part of the modern PHP stack, so if you're not familiar with it I'd highly recommend looking into it - it simplifies dependency management in many ways.

You can get Psr/Log from https://github.com/php-fig/log .

Hope that helps,
Doug

**Comment by darryljackman** [comment]
what about portability between Mac Windows and Linux?

**Comment by dvdoug** [comment]
Composer is written in PHP - it runs anywhere PHP does

**Comment by darryljackman** [comment]
I think it would be easier to not use your code, and attempt functionality myself.. and the fact others have mentioned having the same issue, yet your response is basically "deal with it", rather than propose an alternate (more common way of) of using it (PHP classes) is horrible from a support perspective.. You shouldn't release things for others to use if you aren't at least willing to help facilitate its use.

**Comment by p4dpaul** [comment]
I am tracking changes on this project all the time and so these are popping up in my inbox.

Darryl - you sir are providing nothing to the open source community with your closed way of thinking; you are not enabling change or indeed giving respect and thanks where it is due.

Composer *is* the way we, as a PHP developer community do things these days; you can download the source of this project from GitHub as a zip and hack it about to your hearts content. Take this as constructive feedback; you will get nowhere if you keep doing things the way you are. It's time to open yourself up to change and with it you'll reap the rewards of composer/git/etc - I know because I too had to get my head around composer and installing dependencies that way not long ago, and since I listened and read and took on-board other peoples comments about 'it' as a support tool - i've not looked back.

</twocents>

**Comment by hkvega01** [comment]
> I think it would be easier to not use your code, and attempt functionality myself.. and the fact others have mentioned having the same issue, yet your response is basically "deal with it", rather than propose an alternate (more common way of) of using it (PHP classes) is horrible from a support perspective.. You shouldn't release things for others to use if you aren't at least willing to help facilitate its use.

honestly saying, the demo test code in the "getting start" section is conflicting to their project structure. It is completely unrunnable.
