### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by danielduqma** [dvdoug/BoxPacker#53]
I found a case in which the results are not as expected:
Box:
- 500 (w) X 1000 (l) X 500 (d)

Items:
1. 500 (w) X 500 (l) X 500 (d)
2. 500 (w) X 500 (l) X 250 (d), not keeping it flat
3. 500 (w) X 500 (l) X 250 (d), not keeping it flat

It packs two first items in a box, and last one in another one, but actually they all fit in just one. If I set 2nd and 3rd items to keep flat, it works. Same as if I rotate the box to be 1000 (w) X 500 (l) X 500 (d) or 500 (w) X 500 (l) X 1000 (d).

Thanks

**Comment by dvdoug** [comment]
Hi

Thanks for the report - was this on master, or a released version?

**Comment by danielduqma** [comment]
I found it on master branch.

**Comment by dvdoug** [comment]
OK thanks, I'll use this as a testcase.

Please note the 3D packing is new to master and not in a released version yet precisely because I'm not happy with the performance it yet (current implementation is more about the plumbing than the algorithm) - as you've noticed the 2D version often performs better so I'd recommend sticking with v2.0 for now. When I release a new version with proper 3D support it will be a drop-in replacement.

**Comment by dvdoug** [comment]
This was fixed in v2.2.0
