### ISSUE TITLE
Outer dimensions and box weight

### ISSUE THREAD

**Issue by Ciantic** [dvdoug/BoxPacker#57]
Hello!

I've developed a free (MIT) plugin for WooCommerce (not released yet), I've come up with following settings screen for the plugin:

![image](https://cloud.githubusercontent.com/assets/64731/19142496/6f3b8dbc-8ba6-11e6-824a-706dfee1b9ef.png)

I'm wondering do you use the Outer dimensions of package (and empty weight) to anything? I don't want to add those to the plugin, it would clutter the interface.

If I've understood this correctly the outer dimensions and box weight is irrelevant to the algorithm. Is that right?

Thanks, great plugin. P.S. I wish there were a way to minimize the price, currently the algorithm does not take the price in to account at all.

**Comment by Ciantic** [comment]
*face palm* Of course I need the box weight at least, because otherwise it would be hard to caculate max weight for the whole shipment.

**Comment by Ciantic** [comment]
Settings page looks like this now:

![image](https://cloud.githubusercontent.com/assets/64731/19142903/6683c506-8ba9-11e6-9865-3917e902406b.png)

If you see any errors, since you've thought this problem a lot harder, let me know. I think I don't need the outer dimensions in the table.

**Comment by dvdoug** [comment]
Nice!

The actual packing algorithm only uses the inner dimensions and the empty/max weight of the box.

However, one of the use cases for the library is that you'd take the calculated boxes and then pass those details onto a shipping API to get accurate delivery costs (e.g. international shipping). Or sometimes even when you're charging a flat rate to the end customer, the courier's API requires box dimensions before they'll give you a label. In those cases you'd need the outer measurements, which is why the interface provides for them - so they're easily available alongside the (calculated) weight.

It *is* a lot of numbers, but once it's all set up probably won't need updating frequently.

**Comment by dvdoug** [comment]
Regarding price, every courier/post company has a different pricing structure so they would be a lot of custom work involved there. However, the algorithm does try to use the smallest box(s) possible.
