### ISSUE TITLE
Feature request: Support for decimals / floating point values

### ISSUE THREAD

**Issue by timint** [dvdoug/BoxPacker#605]
I stumbled upon a problem where my client uses floating point values e.g. 12.5 and this produced a seriers of notices, warnings, and errors as the library only seem to support integers. So a wish for floats as a feature implementation.

**Comment by dvdoug** [comment]
Hi @timint 

This is completely intentional - if the library were to use floats, then either it would have to deal with all of the issues surrounding floating point maths (making it very slow)

OR

in many cases things simply wouldn't behave as expected.

Simple example:

```php
<?php
$x = 0.1 + 0.2;
echo ($x <= 0.3) ? 'maths works' : 'maths does not work';
```

If your client really needs fractional values, then you'll need to multiply the sizes of all input dimensions by 10 (and if you use them, divide output dimensions by 10)

**Comment by timint** [comment]
It sound like a whole lot of effort just for fractions.
I ended up passing rounded values as integers to the library.
Thank you for replying.
