### ISSUE TITLE
Idea; add logic to get 'cheapest' option

### ISSUE THREAD

**Issue by breakerh** [dvdoug/BoxPacker#77]
I am working on a shipping module (just for ourself) and for example if you have 2 items. It tries to combine them into 1 box. Eventhough it can be cheaper to send them in 2 boxes. 1 small one, one big one.

I removed the break when it all fits in one box. This way i can bypass it for now. But if you think it comes in handy it could be a possible feature in the future?

So or give priority by costs(or order that the lowest number is the best). Or a simple way to return every single possibility but i don't think that will be the best solution.

What is your idea about this?

ps. big fan of your boxpacker haha :)

**Comment by dvdoug** [comment]
Hmm, that's tricky. In my experience, it's always been cheaper to send a bigger box than than 2 smaller ones!

Is the pricing information for your example publicly available anywhere that I could take a look at?

**Comment by breakerh** [comment]
We use dhl. I don't know if it will be the same where you are from. Here in the Netherlands it is.

**Comment by dvdoug** [comment]
Does NL have a public pricelist? The UK one seems to be http://www.dhl.co.uk/content/dam/downloads/gb/express/shipping/rate_guides/dhl_express_pricing_guide_2017.pdf and at least at first glance I can't see anywhere that makes it cheaper to ship multiple packages.

I'm not looking for proof about what you say, more trying to understand the pricing structure and what kind of algorithm tweaks might be possible.

**Comment by breakerh** [comment]
Can't find a public price table for it.
But a small example.

An car exhaust system (catback) costs 20 euro (second biggest box). 2 pieces will (of course) be 40 euro.
A normal set of headlights will be 7,50 (smallest box). When i try both items (1 exhaust systems and the lights ) it selects  the biggest box instead of the second biggest and one smaller. Which results in nog costing 27,50 but 42,50.
So if you could set a preference or a algorithm to test the cheapest solution that would be awesome.

Am also looking into it myself. But not that quick/pro as you are haha.

**Comment by breakerh** [comment]
ps. if you want i could send you in private the pricelist?

**Comment by dvdoug** [comment]
That would be awesome if you could?

**Comment by breakerh** [comment]
Sure thing, where can i send it too?

**Comment by dvdoug** [comment]
doug@dougwright.me.uk please. Thanks!

**Comment by breakerh** [comment]
ps. sent you a mail ;) Take your time and agian, awesome job on the script man!

**Comment by dvdoug** [comment]
Just FYI I'm still thinking about this - I see 2 main problems

1) What form(s) the additional data needed would actually take - in your case there appears to a flat-rate charge for each type of box, but it's very common for charges to be dependent on the actual packed weight of a box - or even the choice of carrier might be different depending on the weight of the packed box so at that point multiple price lists are in consideration! 

2) Speed - evaluating all of the possible combinations rather than stopping at the best physical fit will take substantially longer. For a store where the typical number of items is just a few that might be fine, but some stores will have a much a larger typical order.

**Comment by dvdoug** [comment]
As things stand I would suggest the best implementation for your specific case would be to call the packer without only the smaller/medium boxes as a possibility and exclude the large one entirely. Then if you get an `ItemTooLargeException`, you could retrigger the packing with the full box selection?

**Comment by breakerh** [comment]
Thanks man! i understand the problems. And funny thing i use the script now in a way you described in your last message. Seems to work, but still want to add it as a functionality when possible (eventually. When i do will also post it here off course).

**Comment by colinmollenhour** [comment]
@dvdoug Would this be as simple as adding a new field like `getSortOrder` and then in the BoxList `compare` method if this field is defined then it is used to sort before the L*W*H? Then the calling code could use it's own rules to set the sort order, such as the dim weight instead of volume, or a cost-adjusted value of the container, etc.

**Comment by dvdoug** [comment]
@colinmollenhour I don't think this can be solved by adjusting the initial sort order, it's about what comes later. Conceptually I see this as needing a wholesale alternative implementation of the core `doVolumePacking()`/`findBestBoxFromIteration()` loop inside `Packer`.

Currently, the loop iterates over all the boxes (smallest first) trying to pack items in. At the end of each pass, the best box is identified, the items inside it are removed from the still-to-be-packed list and the cycle repeats.

Here, the requirement to know that e.g. 1xsmall, 1xmedium should be used instead of 1xextra large requires that the loop is changed so all the possible permutations are calculated to give a resultset like e.g. 1xsmall+1xmedium **OR** 3xsmall **OR** 1xextra large. That entire resultset would then be handed back to the calling application.

Even for relatively low numbers of boxes, I would expect that to become a  _lot_ of additional calculations very quickly so would need to be handled carefully.

Also, thanks for the sponsor! Very much appreciated.

**Comment by colinmollenhour** [comment]
Hi Doug,

I think the case I'm thinking about is more about single packages, although multi-package would be an interesting observation.

Take for example two box options and assume they both will fit the items to be packed:

- 12x8x4 (2.76 lbs minimum of dimensional weight)
- 10x10x4 (2.87 lbs minimum of dimensional weight)

Normally it would be obvious that the 12x8x4 is the best choice. However, if the package + contents weighs say 3.0 pounds then they are equal as far as volume goes so then maybe there are other considerations such as the cost of the box itself. If a "getSortOrder" value was added then the value could be calculated on the fly?

**Comment by dvdoug** [comment]
Potentially, although that does require the assumption that the additional factors are related to purely to the box itself, and not the box+items - e.g. in that example the 10x10x4 might be cheaper cardboard, but the actual shipping cost might be different at 2.8lbs and 3.0lbs so that truly cheaper box is different for different item combinations. If you're getting into those sorts of calculations then I think the best thing would still be for BoxPacker to a return a set of permutations and let the calling app figure out the cost basis for each one

Having said that, your scenario could be implemented already I think

```
class CustomBoxList extends DVDoug\BoxPacker\BoxList
{
    public static function compare($boxA, $boxB): int
    {
    ...
    }
}

$boxList = new CustomBoxList(...);

$packer = new Packer();
$packer->setBoxList($customBoxList);

```

**Comment by colinmollenhour** [comment]
Great points, thanks.

**Comment by bram123** [comment]
@dvdoug We're also running into this issue.
Would you allow a PR that adds `fromArray(array $boxes, bool $preSorted = false): self` to BoxList, just like ItemList?

**Comment by dvdoug** [comment]
@bram123 yes I would, please create it for the 3.x branch though not for master if you'd like a release with it anytime soon 😄
