### ISSUE TITLE
Why does testIssue52C pack into two boxes?

### ISSUE THREAD

**Issue by palodequeso** [dvdoug/BoxPacker#85]
As I sift through this code, this is the one test that I am completely stumped on. Why does it produce two boxes?

**Comment by dvdoug** [comment]
How many are you expecting?

**Comment by palodequeso** [comment]
I'm expecting 1. If you look at the width and length dimensions, they all fit without reorientation inside the box. And the sum of their depths is less than the inner depth of the box as well.

**Comment by dvdoug** [comment]
It's a side-effect of the order the items are packed in - the bulkier ones are chosen to go first at the bottom of box 1 (side by side), but then it's deemed the last item shouldn't be packed on top because of stability issues (the algorithm currently allows for a max 10% overhang of each vertical "layer" above the previous one).

A future version of the lib will enhance the algorithm to consider actual centre of gravity of each of item rather than the current simplification but for now this particular scenario is indeed packed a little sub-optimally.

**Comment by palodequeso** [comment]
Thanks for the explanation!

**Comment by dvdoug** [comment]
This now packs into a single box on master
