### ISSUE TITLE
Strange behavior noticed

### ISSUE THREAD

**Issue by tghelios** [dvdoug/BoxPacker#87]
I noticed strange behavior while using algorithm. I used 2 items, same dimensions and weight and supplied 3 boxes to packing algorithm.

Item:
Weight: 1kg
Length: 1000mm
Width: 1000mm
Height: 1500mm

Box:
weight: 1kg
max weight: 7kg

I supplied 6 quantities for both items. Items are packed in 2 boxes but issue was, 
Box 1 contains 5 of item A and 1 of  item B
Box 2 contains 5 of item  B and 1 of item A.

I was not able to find the reason for this. Because if both items are of same dimensions and weight, item A should in in one box and item B should be in second box.

**Comment by dvdoug** [comment]
Hello

I agree with you the behaviour you've spotted is slightly weird, but I'm not sure if I would class it as a bug or not - I'm having trouble deciding.

Essentially, the library sorts items by various dimensional attributes to place the larger ones at the bottom. If 2 items have identical dimensions, then the library isn't currently specifying a preference and the order of them is currently left up to the details of PHP's internal sort (see https://github.com/dvdoug/BoxPacker/blob/2.x-dev/ItemList.php#L27)

This is because if they are dimensionally equivalent, then the order of them doesn't matter from a volume utilisation standpoint, and saves additional computation time.

Has the "unexpected" ordering actually caused you a problem in any way, or is it just weird enough that you noticed?

**Comment by tghelios** [comment]
Thanks for explanation. I'm using this library for packing item together and get the packaging cost from the customer. 

The problem is, in my testing environment I selected 5 pack of Grapes and 5 pack of Potatoes and library returns 2 boxes, one with 4 pack of Grapes and 1 pack of Potatoes and other box having 4 pack of Potatoes and 1 pack of grapes.  Which actually is weird suggestion for customer. 
Is there a way that we can provide some kind of preference for selecting items?

**Comment by dvdoug** [comment]
Behaviour has been changed in 1.6.2/2.4.2/3.0.0 to sort by description if items are otherwise considered identical
